# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: ATARC-Demo
subtitle: ATARC demo utilizing Jekyll and 18F guides Edit

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: /ATARC-demo

# Author/Organization info to be displayed in the templates
author:
  name: Collin McRae
  url: http://github.com/ATARC-Example/ATARC-Demo

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: ATARC Home
  url: ./
  internal: true
  

# Repo list
# List repos that you would like to appear on the homepage here

# Style Variables
brand_color: "#2cb34a"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
