# Base configuration
permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: redcarpet
pygments: true

# Title
name: DOCter
subtitle: A Jekyll template for project documentation

# When using this template with a project page set the baseurl to '/project-name'
# For local development or user/organization pages set this to an empty string
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/DOCter'